<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'vin' => '1HGBH41JXMN109186',
                'stock_number' => 'STK-2025-001',
                'year' => 2025,
                'make' => 'Toyota',
                'model' => 'Camry',
                'trim' => 'XLE',
                'body_type' => 'Sedan',
                'exterior_color' => 'Celestial Silver Metallic',
                'interior_color' => 'Black',
                'condition' => 'new',
                'mileage' => 12,
                'price' => 32500.00,
                'msrp' => 34500.00,
                'status' => 'available',
                'description' => 'Brand new 2025 Toyota Camry XLE with all the latest features and safety technology.',
                'features' => ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Blind Spot Monitor'],
                'images' => ['/assets/img/vehicles/camry-2025.jpg'],
                'engine' => '2.5L 4-Cylinder',
                'transmission' => 'Automatic',
                'drivetrain' => 'FWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Main Lot - Row A',
            ],
            [
                'vin' => '5YJSA1E26HF177003',
                'stock_number' => 'STK-2024-042',
                'year' => 2024,
                'make' => 'Honda',
                'model' => 'Accord',
                'trim' => 'Sport',
                'body_type' => 'Sedan',
                'exterior_color' => 'Radiant Red Metallic',
                'interior_color' => 'Gray',
                'condition' => 'new',
                'mileage' => 8,
                'price' => 29800.00,
                'msrp' => 31200.00,
                'sale_price' => 28500.00,
                'status' => 'available',
                'description' => '2024 Honda Accord Sport with sporty styling and advanced tech features.',
                'features' => ['Apple CarPlay', 'Android Auto', 'Honda Sensing', 'LED Headlights', 'Dual-Zone Climate'],
                'images' => ['/assets/img/vehicles/accord-2024.jpg'],
                'engine' => '1.5L Turbo',
                'transmission' => 'CVT',
                'drivetrain' => 'FWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Main Lot - Row B',
            ],
            [
                'vin' => '1FMJU1JT7MEA12345',
                'stock_number' => 'STK-2023-089',
                'year' => 2023,
                'make' => 'Ford',
                'model' => 'Escape',
                'trim' => 'SEL',
                'body_type' => 'SUV',
                'exterior_color' => 'Oxford White',
                'interior_color' => 'Ebony',
                'condition' => 'certified_pre_owned',
                'mileage' => 15420,
                'price' => 26900.00,
                'msrp' => 32000.00,
                'status' => 'available',
                'description' => 'Certified Pre-Owned 2023 Ford Escape SEL with low mileage and comprehensive warranty.',
                'features' => ['Power Liftgate', 'Ford Co-Pilot360', 'Wireless Charging', 'Heated Seats', 'Remote Start'],
                'images' => ['/assets/img/vehicles/escape-2023.jpg'],
                'engine' => '1.5L EcoBoost',
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'fuel_type' => 'Gasoline',
                'location' => 'CPO Lot - Row A',
            ],
            [
                'vin' => '3VWDB7AJ5EM123456',
                'stock_number' => 'STK-2025-015',
                'year' => 2025,
                'make' => 'Chevrolet',
                'model' => 'Silverado 1500',
                'trim' => 'LT',
                'body_type' => 'Truck',
                'exterior_color' => 'Black',
                'interior_color' => 'Jet Black',
                'condition' => 'new',
                'mileage' => 5,
                'price' => 48500.00,
                'msrp' => 51000.00,
                'status' => 'available',
                'description' => '2025 Chevrolet Silverado 1500 LT Crew Cab with powerful V8 engine and modern features.',
                'features' => ['Tow Package', 'Bed Liner', 'Rear Camera', 'OnStar', 'Chevy MyLink'],
                'images' => ['/assets/img/vehicles/silverado-2025.jpg'],
                'engine' => '5.3L V8',
                'transmission' => 'Automatic',
                'drivetrain' => '4WD',
                'fuel_type' => 'Gasoline',
                'location' => 'Truck Lot - Row C',
            ],
            [
                'vin' => '2T3P1RFV8MW123789',
                'stock_number' => 'STK-2024-067',
                'year' => 2024,
                'make' => 'Mazda',
                'model' => 'CX-5',
                'trim' => 'Touring',
                'body_type' => 'SUV',
                'exterior_color' => 'Soul Red Crystal',
                'interior_color' => 'Black',
                'condition' => 'new',
                'mileage' => 18,
                'price' => 31200.00,
                'msrp' => 33500.00,
                'status' => 'available',
                'description' => '2024 Mazda CX-5 Touring with premium interior and impressive fuel economy.',
                'features' => ['Mazda Connect', 'Power Moonroof', 'Bose Audio', 'Smart Brake Support', 'Adaptive Cruise'],
                'images' => ['/assets/img/vehicles/cx5-2024.jpg'],
                'engine' => '2.5L 4-Cylinder',
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Main Lot - Row D',
            ],
            [
                'vin' => '5NPD84LF5KH123456',
                'stock_number' => 'STK-2022-145',
                'year' => 2022,
                'make' => 'Hyundai',
                'model' => 'Elantra',
                'trim' => 'SEL',
                'body_type' => 'Sedan',
                'exterior_color' => 'Intense Blue',
                'interior_color' => 'Gray',
                'condition' => 'used',
                'mileage' => 28500,
                'price' => 18900.00,
                'status' => 'available',
                'description' => 'Well-maintained 2022 Hyundai Elantra SEL with one previous owner.',
                'features' => ['Bluetooth', 'Backup Camera', 'Lane Keep Assist', 'Heated Steering Wheel', 'Blind Spot Collision'],
                'images' => ['/assets/img/vehicles/elantra-2022.jpg'],
                'engine' => '2.0L 4-Cylinder',
                'transmission' => 'CVT',
                'drivetrain' => 'FWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Used Lot - Row B',
            ],
            [
                'vin' => 'JM3KFBDM5M0123456',
                'stock_number' => 'STK-2025-008',
                'year' => 2025,
                'make' => 'Nissan',
                'model' => 'Altima',
                'trim' => 'SV',
                'body_type' => 'Sedan',
                'exterior_color' => 'Pearl White',
                'interior_color' => 'Charcoal',
                'condition' => 'new',
                'mileage' => 10,
                'price' => 28400.00,
                'msrp' => 29800.00,
                'status' => 'available',
                'description' => '2025 Nissan Altima SV with advanced safety features and comfortable ride.',
                'features' => ['ProPILOT Assist', 'Intelligent Around View', 'NissanConnect', 'Remote Engine Start', 'Dual Climate'],
                'images' => ['/assets/img/vehicles/altima-2025.jpg'],
                'engine' => '2.5L 4-Cylinder',
                'transmission' => 'CVT',
                'drivetrain' => 'FWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Main Lot - Row A',
            ],
            [
                'vin' => 'WBA5A5C50FD123456',
                'stock_number' => 'STK-2024-098',
                'year' => 2024,
                'make' => 'Subaru',
                'model' => 'Outback',
                'trim' => 'Premium',
                'body_type' => 'SUV',
                'exterior_color' => 'Crystal White Pearl',
                'interior_color' => 'Slate Black',
                'condition' => 'new',
                'mileage' => 15,
                'price' => 35600.00,
                'msrp' => 37200.00,
                'status' => 'available',
                'description' => '2024 Subaru Outback Premium with legendary AWD and rugged capability.',
                'features' => ['EyeSight Driver Assist', 'Roof Rails', 'All-Weather Package', 'STARLINK', 'X-Mode'],
                'images' => ['/assets/img/vehicles/outback-2024.jpg'],
                'engine' => '2.5L Boxer',
                'transmission' => 'CVT',
                'drivetrain' => 'AWD',
                'fuel_type' => 'Gasoline',
                'location' => 'Main Lot - Row C',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Inventory::create($vehicle);
        }

        $this->command->info('Inventory seeded successfully with ' . count($vehicles) . ' vehicles.');
    }
}
